export const ROUTES = {
  root: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  fleet: '/fleet',
  vehicles: '/vehicles',
  drivers: '/drivers',
  maintenance: '/maintenance',
  trips: '/trips',
  reports: '/reports',
  analytics: '/analytics',
  fuelExpenses: '/fuel-expenses',
  settings: '/settings',
  admin: '/admin',
  userManagement: '/user-management',
  safetyReports: '/safety-reports',
  licenseMonitoring: '/license-monitoring',
  profile: '/profile',
};
